name: main

on:
  schedule:
    - cron: "*/1 * * * *" # runs every minute

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      - shell: bash
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
      - name: Git checkout
        uses: actions/checkout@v2
        with: { ref: master }
      - name: Update data
        run: |
          bash run.sh SECRET_KEY

