name: main

on:
  schedule:
    - cron: "*/3 * * * *" # runs every third minute

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: master }
    - name: Update data
      run: |
        sh run.sh

